services:
  ddns:
    build: .
    restart: unless-stopped
    volumes:
      - ddns_state:/data
    environment:
      - CLOUDFLARE_API_TOKEN
      - CLOUDFLARE_ZONE_ID
      - CLOUDFLARE_DNS_NAMES 

volumes:
  ddns_state:

